[package]
name = "ebook_parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
zip = "2.2"
quick-xml = "0.36"
serde = { workspace = true }
thiserror = "2.0"
